apiVersion: v1
kind: Secret
metadata:
  name: compass-worker-secrets
  namespace: compass
type: Opaque
stringData:
  PG_DSN: "postgresql://compass:CHANGEME@postgres.compass.svc.cluster.local:5432/compass"
  CH_PASSWORD: ""